#!/bin/bash

set -ue

pushd $(git rev-parse --show-toplevel)
make doc >/dev/null

set +e
git diff --exit-code --quiet docs
DIFF_EC=$?
set -e

if [ ${DIFF_EC} -ne 0 ]; then
  echo "There are unstaged documents."
  echo "Please stage files under docs."
  exit 1
fi

popd

pushd test/unittest
./test_all.sh
popd
