#!/bin/bash

set -ue

pushd $(git rev-parse --show-toplevel)
if [ ! -d docs ]; then
  make doc
  git diff docs --exit-code --quiet
  if [ $? -eq 0 ]; then
    echo "There are unstaged documents."
    echo "Please stage files under docs."
    exit 1
  fi
fi
popd

pushd test/unittest
./test_all.sh
popd
