name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx: ["g++", "clang++"]
        cxx_ver: ["c++17", "c++20", "c++2b"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build gtest
        run: |
          cd test/unittest
          ./build_gtest.sh
      - name: "test g++ C++17"
        run: |
          cd test/unittest
          make CXX=${{cxx}} CXX_VER=${{cxx_ver}} clean test
