name: gcc tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: byplayer/gcc-cmake:13
    strategy:
      matrix:
        cxx: ["g++"]
        cxx_ver: ["c++17", "c++20", "c++2b"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build gtest
        run: |
          cd test/unittest
          ./build_gtest.sh g++
      - name: "build and run unit tests"
        run: |
          cd test/unittest
          make CXX=${{matrix.cxx}} CXX_VER=${{matrix.cxx_ver}} test
